version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 428056470896.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t mailbotecr .
      - docker tag mailbotecr:latest 428056470896.dkr.ecr.us-east-1.amazonaws.com/mailbotecr:latest

  post_build:
    commands:
      - docker push 428056470896.dkr.ecr.us-east-1.amazonaws.com/mailbotecr:latest
